DSS-474: feat() - Add `error-message` to radio & checkbox
Kajabi/pine pull request #111
Opened 2023-09-27 17:11 UTC by pixelflips

# Description

The checkbox and radio are missing the separate `error-message` prop.
This adds the `error-message` prop, documentation, and tests to match other components.

Fixes [DSS-474](https://kajabi.atlassian.net/browse/DSS-474)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- Navigate to the checkbox and radio.
- Verify error-message displays as expected.
- Verify that error-message tests pass as expected. (`yarn nx run core:test`)

- [x] unit tests
- [x] tested manually

**Test Configuration**:

- Pine versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2023-09-28 21:50 UTC, QuintonJason requested changes
Great job getting this in parity! Only issue I currently see is that when the checkbox / radio is invalid the helper text should not match the error color as the helper text doesn't change color when an error is present, similar to switch.

2023-09-28 21:57 UTC, pixelflips commented
> Great job getting this in parity! Only issue I currently see is that when the checkbox / radio is invalid the helper text should not match the error color as the helper text doesn't change color when an error is present, similar to switch.

@QuintonJason great catch. I'll get that adjusted, thanks for the heads up!

2023-09-28 22:20 UTC, QuintonJason approved these changes
Nice work!

2023-10-06 16:06 UTC, ju-Skinner approved these changes

2023-10-06 20:42 UTC, merged