feat(react): add PdsIcon helper
Kajabi/pine pull request #126
Opened 2023-12-13 21:19 UTC by ju-Skinner

# Description

Adds PdsIcon helper to the react library. This is required to pass the `icon` property using React SVG imports.

Fixes #(issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

If not applicable, leave options unchecked.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2023-12-13 21:39 UTC, pixelflips requested changes
A couple of small comments. If those are intentional, just let me know.

2023-12-13 21:39 UTC, pixelflips commented on libs/core/src/components/pds-radio/readme.md
> +| `errorMessage`             | `error-message`  | Displays message text describing an invalid state.                                                  | `string`  | `undefined` |
are these changes related?

2023-12-13 21:39 UTC, pixelflips commented on libs/react/src/components/PdsIcon.tsx
> +        'In Pine React, you import icons from "@ju-skinner/ideal-octo-sniffle" and set the icon you imported to the "name" property. Setting the "name" property has no effect.'
is that the correct location?

2023-12-13 22:14 UTC, pixelflips approved these changes
LGTM!

2023-12-14 18:40 UTC, anechol approved these changes

2023-12-14 18:58 UTC, merged