feat(button): add css shadow parts
Kajabi/pine pull request #142
Opened 2024-02-08 22:32 UTC by pixelflips

# Description

Adds CSS shadow parts to the button component. This will expose the parts making up the buttons to allow styling of the button component when it's placed within other components.

Fixes #DSS-523

## Type of change

Please delete options that are not relevant.
If your type of change is not present, add that option.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests you've added and run to verify your changes.
Provide instructions so that we can reproduce.
Please also list any relevant details for your test configuration.

- [ ] unit tests
- [ ] e2e tests
- [ ] accessibility tests
- [x] tested manually
- [ ] other:

**Test Configuration**:

- Pine versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2024-02-09 13:20 UTC, ju-Skinner requested changes
Good morning,

Everything looks good. You are just missing the TSDoc comments which will add the descriptions to the parts.

2024-02-09 13:20 UTC, ju-Skinner commented on libs/core/src/components/pds-button/pds-button.tsx
you need to add this above line 4. This will add the descriptions to both the `readme.md` and the Args Table in storybook. 

```
/**
 * @part button - [SOME DESCRIPTION[
 * @part caret - [SOME DESCRIPTION[
 * @part icon - [SOME DESCRIPTION[
 */

2024-02-09 17:40 UTC, ju-Skinner approved these changes
Great job 👏🏾

2024-02-12 17:35 UTC, anechol approved these changes

2024-02-12 18:46 UTC, merged