Fix/progress bar not showing in storybook
Kajabi/pine pull request #185
Opened 2024-05-01 19:28 UTC by ju-Skinner

# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
List any new dependencies or updates that are required for this change.

|Before|After|
|-----|----|
|![image](https://github.com/Kajabi/pine/assets/1633290/015a7873-1dfc-4713-895c-3ce74f177e95)|![image](https://github.com/Kajabi/pine/assets/1633290/d299b3bf-71aa-43af-8536-f890d82fd72a)|

Fixes #(issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documenation

# How Has This Been Tested?

- [x] tested manually
- [x] other: Storybook

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2024-05-01 19:30 UTC, pixelflips requested changes

2024-05-01 19:30 UTC, pixelflips commented on libs/core/src/components/pds-progress/pds-progress.scss
> +    width: var(--sizing-progress-bar-width);
i think that shouldn't change

2024-05-01 19:36 UTC, pixelflips approved these changes

2024-05-03 16:45 UTC, QuintonJason approved these changes
Looks and works great

2024-05-03 16:50 UTC, merged