[DSS-306] add dark mode to Storybook
Kajabi/pine pull request #20
Opened 2023-02-14 21:02 UTC by QuintonJason

# Description
This is a followup PR to https://github.com/Kajabi/sage/pull/18 as there was an error blocking the initial work
- [x] Add dark mode functionality to storybook
- [ ] Add dark theme to storybook

**Dependencies**
- `storybook-dark-mode`
- `babelOptions`

Fixes #(issue)
[DSS-306](https://kajabi.atlassian.net/browse/DSS-306)

## Type of change
- [x] This change requires a documentation update

# How Has This Been Tested?
No tests provided, docs only

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

2023-02-22 14:59 UTC, ju-Skinner requested changes
See comments about the dependencies.

2023-02-22 14:59 UTC, ju-Skinner commented on libs/core/package.json
> +    "@babel/plugin-syntax-jsx": "^7.18.6",
this needs to be under `devDependencies`. You can just cut and paste it and re-run `yarn setup`. Be sure to commit the `yarn.lock` as well.

2023-02-22 14:59 UTC, ju-Skinner commented on libs/core/package.json
> +    "@babel/plugin-syntax-jsx": "^7.18.6",
Looks like you have it in here twice. Just remove the one under `dependencies`.

2023-02-22 15:34 UTC, QuintonJason commented on libs/core/package.json
> +    "@babel/plugin-syntax-jsx": "^7.18.6",
Updated. No `yarn.lock` change since this already existed in `devDependencies`

2023-02-22 15:48 UTC, goodwinchris commented
This appears to be working well but some of our components don't work on a dark canvas, should we be styling canvases to be white even in dark mode? 
<img width="1058" alt="CleanShot 2023-02-22 at 10 47 44@2x" src="https://user-images.githubusercontent.com/791670/220677413-95ffa29f-9602-4802-b75d-16c2faf4ac8a.png">

2023-02-24 16:59 UTC, QuintonJason commented
Putting this PR into Draft as there are additional complications with the style switching. We'll revisit this after discovery with Storybook Doc 7 beta

2023-12-19 14:34 UTC, QuintonJason commented
Closing this PR as Storybook now is updated to Storybook 7

2023-12-19 14:34 UTC, closed without merging