Tokens - Adds New Rebrand Colors
Kajabi/pine pull request #222
Opened 2024-07-09 20:09 UTC by anechol

# Description

Adds in new color tokens for the rebrand. 

[DSS-667](https://kajabi.atlassian.net/browse/DSS-667)

## Type of change

- [x] Token change (adds, updates, or removes design tokens)

# How Has This Been Tested?

Please describe the tests you've added and run to verify your changes.
Provide instructions so that we can reproduce.
Please also list any relevant details for your test configuration.

- [ ] unit tests
- [ ] e2e tests
- [ ] accessibility tests
- [x] tested manually
- [ ] other:

**Test Configuration**:

- Pine versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2024-07-10 18:36 UTC, ju-Skinner approved these changes
LGTM

2024-07-10 18:59 UTC, ju-Skinner commented
I have some additional questions about the number scale. I'll circle back after our meeting later today.

2024-07-10 20:21 UTC, anechol commented
@ju-Skinner Tokens have been updated

2024-07-10 22:13 UTC, ju-Skinner approved these changes

2024-07-11 14:40 UTC, monicawheeler requested changes
Sounds like I am +1'ing Julian but to be sure, the color scale has appeared to be changed to a 10s scale
![image](https://github.com/Kajabi/pine/assets/24237393/30ec49b0-1262-4795-862c-755c2c8140f0)

2024-07-11 18:28 UTC, anechol commented
> Sounds like I am +1'ing Julian but to be sure, the color scale has appeared to be changed to a 10s scale ![image](https://private-user-images.githubusercontent.com/24237393/347866588-30ec49b0-1262-4795-862c-755c2c8140f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjI4MDEsIm5iZiI6MTcyMDcyMjUwMSwicGF0aCI6Ii8yNDIzNzM5My8zNDc4NjY1ODgtMzBlYzQ5YjAtMTI2Mi00Nzk1LTg2MmMtNzU1YzJjODE0MGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE4MjgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZWE2NjI0ZDE2MGNjNGQwNDNkNDU5ZTRmYWM5MDRjMGNjZGQzOWE2MDYxOWE0YTM2OGZiOWExYmYxOGQ2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MN0VL7Hif8y-ap6hfF-OR-m6kqxW7i4THmWw5Uq7ZwI)

@monicawheeler Per team discussion, we've decided to move forward with the 100 scale tokens.

2024-07-11 18:44 UTC, pixelflips approved these changes
One minor comment, otherwise LGTM! Nice work!

2024-07-11 18:44 UTC, pixelflips commented on libs/core/src/global/styles/tokens/core/_core.scss
> +  --pine-color-gray-50: #fcfcfc;
after today's critique meeting, we've agreed to stay with the `grey` naming for now.

2024-07-11 21:03 UTC, merged