fix: update font size refs
Kajabi/pine pull request #239
Opened 2024-08-12 17:26 UTC by QuintonJason

# Description
- [x] replace font-size `087` with `85`

|  Before  |  After  |
|--------|--------|
|![Screenshot 2024-08-12 at 11 41 23 AM](https://github.com/user-attachments/assets/985010c1-c9a1-4782-a3bf-077446363139)|![Screenshot 2024-08-12 at 12 25 25 PM](https://github.com/user-attachments/assets/1b5998c6-7d9b-4d83-bcd6-648e433bb879)|

Fixes #(issue)
[DSS-790](https://kajabi.atlassian.net/browse/DSS-790)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2024-08-12 17:27 UTC, pixelflips approved these changes

2024-08-12 17:28 UTC, pixelflips approved these changes

2024-08-12 17:28 UTC, ju-Skinner commented on libs/core/src/components/pds-chip/pds-chip.scss
> +  --font-size-sm: var(--pine-font-size-85);
is there a reason why it's not `085`? It seems all other two digits follow the three digit placeholder sequence

2024-08-12 21:52 UTC, ju-Skinner commented on libs/core/src/components/pds-link/pds-link.scss
> +  --font-size-sm: var(--pine-font-size-85);
Here we are using `85` but below we are using `075`, why the inconsistency?

2024-08-12 21:57 UTC, ju-Skinner requested changes
There is an inconsistency between the token values for this change. It appears that all tokens should be changed to a non three-digit placeholder if they are only one or two digits.

2024-08-12 23:10 UTC, anechol requested changes
Let's discuss these token name changes post-demo.

2024-08-13 17:10 UTC, ju-Skinner commented on libs/core/src/components/pds-chip/pds-chip.scss
> +  --font-size-sm: var(--pine-font-size-085);
So are all tokens that include digits using three placeholder

2024-08-13 17:23 UTC, pixelflips commented on libs/core/src/components/pds-accordion/pds-accordion.scss
> +  --spacing-details-padding-block-end: calc(var(--pine-spacing-200) + 2) //18 + 2 = 18px;
I'd be curious to understand the calculations here vs prev token usage. Not a blocker

2024-08-13 17:26 UTC, pixelflips approved these changes
Couple of comments, otherwise LGTM!

2024-08-13 17:26 UTC, pixelflips commented on libs/core/src/components/pds-link/pds-link.scss
> +  --border-radius: var(--pine-border-radius-75);
missing 0?

2024-08-13 17:39 UTC, anechol approved these changes

2024-08-13 17:40 UTC, merged