Docs/box row updates
Kajabi/pine pull request #350
Opened 2024-12-13 19:57 UTC by QuintonJason

# Description

- [x] Updates Layout documentation 
- [x] resolve specificity issue

Fixes [DSS-1173](https://kajabi.atlassian.net/browse/DSS-1173)

2024-12-13 20:45 UTC, pixelflips approved these changes

2024-12-16 16:29 UTC, monicawheeler requested changes
![Screenshot 2024-12-16 at 10 28 25 AM](https://github.com/user-attachments/assets/c4bbc1ca-463a-4e1d-957b-d243280d5b7a)

It appears that the image is not rendering. Could we get this updated to show the image?

2024-12-16 16:30 UTC, ju-Skinner approved these changes

2024-12-16 17:16 UTC, QuintonJason commented
> ![Screenshot 2024-12-16 at 10 28 25 AM](https://private-user-images.githubusercontent.com/24237393/396179621-c4bbc1ca-463a-4e1d-957b-d243280d5b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjk2NDgsIm5iZiI6MTczNDM2OTM0OCwicGF0aCI6Ii8yNDIzNzM5My8zOTYxNzk2MjEtYzRiYmMxY2EtNDYzYS00ZTFkLTk1N2ItZDI0MzI4MGQ1YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE3MTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYmU2MWI4MGM3MDE4ZmY1ZGMxNWIwMDM5ZTA2NzMyYTQ4Y2U5ODAwYWFlNWE4MmYwOWEzOTJmYjlmNjk0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VPqFHfx56bU8eSMQ2qKrywjvDHHJ0lx9E4o0v8MR0Cw)
> 
> It appears that the image is not rendering. Could we get this updated to show the image?

@monicawheeler pushed a fix

2024-12-16 18:35 UTC, monicawheeler approved these changes

2024-12-16 19:49 UTC, merged