docs: updates README and adds CONTRIBUTING file
Kajabi/pine pull request #355
Opened 2024-12-17 17:54 UTC by anechol

# Description

Updates the README file as well as adds a new CONTRIBUTING file.

This is an initial draft so if there's anything that should be added, updated, fixed, or removed, please feel free to recommend.

[DSS-1208](https://kajabi.atlassian.net/browse/DSS-1208)

## Type of change

- [x] Documentation (adds, removes, or updates project documentation)

2024-12-17 17:59 UTC, pixelflips approved these changes

2024-12-17 18:35 UTC, QuintonJason approved these changes
These are really good

2025-01-06 15:17 UTC, ju-Skinner requested changes
This looks good. There is one thing to add, which is how to use the react version of the components. Once we add that this is good to go.

2025-01-13 18:36 UTC, ju-Skinner approved these changes

2025-01-13 18:50 UTC, merged