feature(sage-icon) - add color prop to sage icon
Kajabi/pine pull request #64
Opened 2023-05-31 14:22 UTC by ju-Skinner

# Description

Adding the `color` attribute to allow customers to specify a color they would like the icon to be rendered. The attribute allows both string and hex formats

Fixes #(issue)
https://kajabi.atlassian.net/browse/DSS-283

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests you've added and run to verify your changes.
Provide instructions so that we can reproduce.
Please also list any relevant details for your test configuration.

- [x] unit tests
- [ ] e2e tests
- [ ] accessibility tests
- [x] tested manually
- [x] other: Storybook

**Test Configuration**:

- Sage versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2023-05-31 15:13 UTC, ju-Skinner commented
Please note that there is a dependency on PR #62. This PR CANNOT be merged until its dependency has been merged. Thank you.

2023-06-01 17:57 UTC, QuintonJason requested changes
Good stuff. Left a couple comments.

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.tsx
> +
Delete this line

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/package.json
> +    "test.watch": "stencil test --spec --e2e --watch --coverage",
🏆 Nice add

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.scss
> +  box-sizing: content-box;
I'm not sure if this is doing anything, does this need to be here?

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.scss
> +
Please remove the spaces between the rules here and above in this declaration

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.scss
> +// Icon Sizes
Remove the white space on line 26

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.scss
> +:host(.sage-icon-small) {
The icon size looks like it's being determined by the inline `style`s, does this section still need to exist?

2023-06-01 17:57 UTC, QuintonJason commented on libs/icons/src/components/sage-icon/sage-icon.tsx
> +
Remove the extra space

2023-06-01 19:15 UTC, QuintonJason approved these changes
Great work on this PR! Good to go

2023-06-06 15:45 UTC, pixelflips approved these changes
LGTM! 👍🏼

2023-06-06 16:14 UTC, merged