[DSS-412] aria-describedby message form utility
Kajabi/pine pull request #65
Opened 2023-06-02 17:31 UTC by QuintonJason

# Description
Inspired by Kevin's addition in his [Switch PR](https://github.com/Kajabi/sage/pull/55). The PR moves the functions, `assignDescription` and `messageId`, into the `utils` directory and call them in the all form elements that will have helper text

- [x] move functions to utility folder
- [x] update tests accordingly
- [x] make the componentId required for all form elements

Fixes #(issue)
[DSS-412](https://kajabi.atlassian.net/browse/DSS-412)

|  Before  | After  |
|---|---|
|![Screen_Shot_2023-06-02_at_2_30_01_PM](https://github.com/Kajabi/sage/assets/1241836/a03a21b3-0506-4732-ae46-22c7b5ac753c)|![Screen_Shot_2023-06-02_at_2_24_33_PM](https://github.com/Kajabi/sage/assets/1241836/0088c21f-633c-4a9c-92d5-2f8c2ecf3425)|

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests you've added and run to verify your changes.
Provide instructions so that we can reproduce.
Please also list any relevant details for your test configuration.

Visit the following helper text views for the corresponding form element component and verify, by using the inspector, that the helper text has an `id` that corresponds to the `aria-describedby` for the field:

- [Checkbox](http://localhost:6006/?path=/story/components-checkbox--with-message)
- [Input](http://localhost:6006/?path=/story/components-input--hint)
- [Switch](http://localhost:6006/?path=/story/components-switch--helper-message)
- [Textarea](http://localhost:6006/?path=/story/components-textarea--hint)

## Testing
- [x] unit tests
- [x] e2e tests
- [x] accessibility tests
- [ ] tested manually
- [ ] other:

**Test Configuration**:

- Sage versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

[DSS-412]: https://kajabi.atlassian.net/browse/DSS-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-06 18:23 UTC, pixelflips reviewed
In the input component, I believe the component-id is missing from the examples. This is causing the id on the message and the aria-describedby to contain undefined in the generated strings.


See screenshot:

<img width="699" alt="Screenshot 2023-06-06 at 11 21 38 AM" src="https://github.com/Kajabi/sage/assets/1175111/79e3dc1d-df8b-409e-b064-3ddfefa44f32">

2023-06-06 19:45 UTC, QuintonJason commented
> In the input component, I believe the component-id is missing from the examples. This is causing the id on the message and the aria-describedby to contain undefined in the generated strings.
> 
> See screenshot:
> 
> <img alt="Screenshot 2023-06-06 at 11 21 38 AM" width="699" src="https://user-images.githubusercontent.com/1175111/243791618-79e3dc1d-df8b-409e-b064-3ddfefa44f32.png">

Great catch! Added a ticket, https://kajabi.atlassian.net/browse/DSS-417, to address this for this and any case where the developer needs to be alerted

2023-06-06 20:19 UTC, pixelflips approved these changes
Nice work and thanks for the additional clean up as well. LGTM! 👍🏼

2023-06-07 18:48 UTC, ju-Skinner commented on libs/core/src/utils/form.spec.ts
may not now, but would love to have the test moved to a sub-folder `test`.

2023-06-07 18:55 UTC, ju-Skinner requested changes
See comments below. TL;DR need test for `form` helper functions

2023-06-07 18:55 UTC, ju-Skinner commented on libs/core/src/utils/form.spec.ts
> +});
We should have multiple test for `assignDescription` that covers the various scenarios.

* helperMessage null or undefined
* invalid both true or false
* happy path scenarios

We also need to add test for `messageId`

2023-06-13 21:17 UTC, pixelflips approved these changes
LGTM! Rechecked each form input and the new attributes are showing up properly. Great work! 👍🏼

2023-06-13 21:59 UTC, ju-Skinner commented on libs/core/src/components/pds-input/stories/pds-input.docs.stories.mdx
> +    invalid: false,
Do we want an example that shows "invalid"?

2023-06-14 15:10 UTC, ju-Skinner approved these changes

2023-06-14 15:23 UTC, merged