chore: rename components to "pds"
Kajabi/pine pull request #68
Opened 2023-06-06 15:00 UTC by ju-Skinner

# Description

This is a PR that will rename the components and processes to use the new Design System name. The currently agreed naming is as follows:

Component prefix: `pds` e.g `pds-icon`
Component Class Name: `Pds[ComponentName]` e.g `PdsIcon`
Tokens prefix: `--pine` e.g `--pine-background-color`

2023-06-06 16:13 UTC, pixelflips approved these changes
A couple of non-blocking comments, but overall LGTM! 👍🏼

2023-06-06 16:13 UTC, pixelflips commented on libs/core/src/components/pds-icon/pds-icon.docs.stories.mdx
>  Displays Icons used with the Sage Design System
Should Sage be updated here?

2023-06-06 16:13 UTC, pixelflips commented on libs/icons/src/index.html
>      <h1>Sage Icons</h1>
Should Sage be updated here?

2023-06-06 16:32 UTC, ju-Skinner commented on libs/core/src/components/pds-icon/pds-icon.docs.stories.mdx
>  Displays Icons used with the Sage Design System
Good catch. Thank you,

2023-06-06 16:34 UTC, ju-Skinner commented on libs/icons/src/index.html
>      <h1>Sage Icons</h1>
Another good  catch.

2023-06-06 17:40 UTC, QuintonJason approved these changes
Good to go!

2023-06-06 18:24 UTC, anechol approved these changes

2023-06-07 16:05 UTC, pixelflips approved these changes
Checked the latest round of updates and all seem fine and working as expected. Others broke due to token name changes, but that's to be expected. Great work! 👍🏼

2023-06-08 15:25 UTC, QuintonJason approved these changes
Everything up to input looks good

2023-06-08 16:21 UTC, teenwolfblitzer approved these changes
😎 LGTM. Safe to assume the static elements (branding, "get support" page) will be updated separately?

2023-06-08 19:51 UTC, ju-Skinner commented
> 😎 LGTM. Safe to assume the static elements (branding, "get support" page) will be updated separately?

Yes, you are correct @monkeypox8. Things like

* CDN / Brand URLs
* Images

2023-06-08 20:18 UTC, QuintonJason approved these changes
Good stuff

2023-06-08 20:29 UTC, pixelflips requested changes
Found a minor styling issue, otherwise looks good.

Not sure if an update is needed now, but the `libs/core/src/stories/Support.stories.mdx` file also mentions Sage.

2023-06-08 20:29 UTC, pixelflips commented on libs/core/src/components/pds-textarea/pds-textarea.scss
> +  border-radius: var(pine-border-radius-md);
These are missing the `--` in the variable names

2023-06-09 03:38 UTC, ju-Skinner commented
> Found a minor styling issue, otherwise looks good.
> 
> Not sure if an update is needed now, but the `libs/core/src/stories/Support.stories.mdx` file also mentions Sage.

I fixed the story...You can see the change in the `fixup` commit. I'll squash it once everyone gets their review complete.

2023-06-09 20:18 UTC, pixelflips approved these changes
LGTM! Nice work!

2023-06-09 21:52 UTC, anechol approved these changes
LGTM

2023-06-09 22:53 UTC, monkeypox8 approved these changes
🌲

2023-06-12 02:29 UTC, merged