DSS-458: Docs - Display Custom Events in Actions Tab
Kajabi/pine pull request #95
Opened 2023-08-28 22:18 UTC by pixelflips

# Description

Updates Storybook stories so that custom event data is displayed in the actions panel vs. using custom console.log which requires using browser dev tools.

Fixes [DSS-458](https://kajabi.atlassian.net/browse/DSS-458)

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2023-08-29 17:44 UTC, ju-Skinner approved these changes
:shipit:

2023-08-30 00:36 UTC, QuintonJason requested changes
This is great work and I love how this scales. Can you add the remaining custom events for the following components?
- `pds-chip` -> `pdsTagCloseClick`
- `pds-tooltip` -> `pdsTooltipHide`
- `pds-tooltip` -> `pdsTooltipShow`

2023-08-30 15:33 UTC, anechol approved these changes
This is great, thanks for adding this

2023-08-30 16:33 UTC, pixelflips commented
> This is great work and I love how this scales. Can you add the remaining custom events for the following components?
> 
> * `pds-chip` -> `pdsTagCloseClick`
> * `pds-tooltip` -> `pdsTooltipHide`
> * `pds-tooltip` -> `pdsTooltipShow`

Added all of these and requested another review. Thanks for catching those!

2023-08-30 16:42 UTC, QuintonJason approved these changes
Great work!

2023-08-30 17:43 UTC, merged