DSS-461: fix(button) - Replace hard coded icon + styling
Kajabi/pine pull request #97
Opened 2023-08-31 16:56 UTC by pixelflips

# Description
The icon within the button component is currently hard coded. These updates replace the hard-coded icon and adjusts styling.

Fixes: DSS-461

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

1. Navigate to the button component.
2. Verify icons appear properly when selecting an icon.
3. Verify buttons visually appear as expected.

- [ ] unit tests
- [ ] e2e tests
- [ ] accessibility tests
- [ ] tested manually
- [ ] other:

**Test Configuration**:

- Pine versions:
- OS:
- Browsers:
- Screen readers:
- Misc:

# Checklist:

If not applicable, leave options unchecked.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Design has QA'ed and approved this PR

2023-08-31 22:40 UTC, ju-Skinner requested changes
I will fix these before EOD today, August 31.

2023-08-31 22:40 UTC, ju-Skinner commented on libs/core/src/stories/_helpers/index.ts
> +}
@pixelflips we need to remove this since we created a new function.

2023-08-31 22:40 UTC, ju-Skinner commented on libs/core/src/stories/_helpers/index.ts
> + * @returns object
Need to add `property` to the TSDoc comments.

2023-09-01 01:35 UTC, ju-Skinner approved these changes
great job!!!

2023-09-05 18:59 UTC, QuintonJason approved these changes
Good to go!

2023-09-05 19:00 UTC, merged